repos:
  - repo: builtin
    hooks:
      - id: check-added-large-files
        exclude: |
          (?x)(
              ^*.png|
              ^*.jpg
          )
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: check-toml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # - id: debug-statements # Fails to parse the __init__.py file
      - id: name-tests-test
        args: ["--pytest-test-first"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.20
    hooks:
      # first, lint + autofix
      - id: ruff-check
        types_or: [python, pyi, jupyter]
        args: [--fix, --show-fixes]
      # then, format
      - id: ruff-format

  - repo: https://github.com/lyz-code/yamlfix
    rev: 1.19.1
    hooks:
      - id: yamlfix
        exclude: |
          (?x)(
              ^.copier-answers.yml|
              ^.pre-commit-config.yaml|
              ^firmware/.clang-format
          )

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.11.15
    hooks:
      - id: uv-lock

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v22.1.2
    hooks:
    - id: clang-format
      types_or: [c++, c]
      args: [-style=file:firmware/.clang-format]
