site_name: Documentation

nav:
  - Home: index.md
  - Firmware:
      - Limitations: firmware/limitations.md
      - Improvements: firmware/improvements.md

theme: material

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - autorefs:
      resolve_closest: true
  - mkdocstrings:
      handlers:
        python:
          options:
            show_submodules: true
