# APPLICATION CONFIGURATION
#CONFIG_MIDGE_IMU_ICM20948_USE_CLOSED_DRIVER=n


# General
CONFIG_STD_C17=y
CONFIG_GNU_C_EXTENSIONS=y
CONFIG_CRC=y
CONFIG_REBOOT=y

CONFIG_PRINTK=y
CONFIG_LOG=y
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_OUTPUT_DISASSEMBLY=y

#CONFIG_MISRA_SANE=y
#CONFIG_CODING_GUIDELINE_CHECK=y
CONFIG_COMPILER_WARNINGS_AS_ERRORS=y

# Bluetooth
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_ZEPHYR_NUS=y
CONFIG_BT_OBSERVER=y
CONFIG_BT_DEVICE_NAME="MingleMidge"
CONFIG_BT_MAX_CONN=1
CONFIG_BT_RX_STACK_SIZE=4098
# FASTER DOWNLOAD SPEED
CONFIG_BT_BUF_ACL_TX_COUNT=9
CONFIG_BT_BUF_EVT_RX_COUNT=10

# IMU
CONFIG_I2C=y
CONFIG_GPIO_ENABLE_DISABLE_INTERRUPT=y

# Audio
CONFIG_AUDIO=y
CONFIG_AUDIO_DMIC=y

# Battery charge
CONFIG_GPIO=y
CONFIG_ADC=y

# SDMMC
CONFIG_DISK_ACCESS=y
CONFIG_FILE_SYSTEM=y
CONFIG_FAT_FILESYSTEM_ELM=y
# need to add to doc
CONFIG_FS_FATFS_REENTRANT=y
CONFIG_FILE_SYSTEM_MKFS=y
# FILE_TYPE_MAX in storage.h + 1 for timesync file
CONFIG_FS_FATFS_NUM_FILES=8

# Mover a un overlay de conf (?)
CONFIG_DISK_DRIVER_SDMMC=y
CONFIG_SPI=y
CONFIG_BOOTLOADER_MCUBOOT=n

# PWM
CONFIG_LED=y

#CONFIG_TIMESLICE_SIZE=5
CONFIG_TIMESLICING=y
CONFIG_MAIN_THREAD_PRIORITY=0
#CONFIG_SCHED_SIMPLE=y

# callbacks command
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
