CONFIG_DEBUG=n
CONFIG_DEBUG_OPTIMIZATIONS=n # Equivalent to -Og
CONFIG_SPEED_OPTIMIZATIONS=y # Equivalent to -O2
CONFIG_CONSOLE=n
CONFIG_RTT_CONSOLE=n

# Required by LTO - still under testing for this application
# CONFIG_ISR_TABLES_LOCAL_DECLARATION=y
# CONFIG_LTO=y
