name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Replace 'main' with your default branch name if necessary

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      id-token: write
      pages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7
        with:
          version: latest

      - name: Install the project and its dependencies
        run: uv sync

      - name: Build and deploy with zensical
        run: uv run zensical build --clean

      - uses: actions/upload-pages-artifact@v4
        with:
          path: site

      - uses: actions/deploy-pages@v4
        id: deployment
